### ISSUE TITLE
Falsche lineare Gleichung

### ISSUE THREAD

**Issue by ngnlTeto** [SaschaKersken/ITHandbuch10#1]
Hallo Herr Kersken,

ich lese aktuell mit meinem Ausbilder und einem weiteren Azubi Ihr Buch und wir glauben einen Fehler auf **Seite 103** gefunden zu haben, auf den wir Sie aufmerksam machen möchten. Beim Auflösen der dort beschriebenen **linearen Gleichung** addieren Sie 5 und 5, was in der Rechnung 0 zur Folge hat, wo wir allerdings glauben, das hier mit -5 aufgelöst werden muss.

Viele Grüße.
Henry

**Comment by SaschaKersken** [comment]
Vielen Dank für den korrekten Hinweis. Wird sofort in die Errata-Liste aufgenommen.
